// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsQ_GJPx5TsvFDaQ_ifYDX5dxN8Bqfs2o',
    appId: '1:458679375327:web:1be46f3bd2c69f8eab606a',
    messagingSenderId: '458679375327',
    projectId: 'client1-d8775',
    authDomain: 'client1-d8775.firebaseapp.com',
    storageBucket: 'client1-d8775.appspot.com',
    measurementId: 'G-XF1LTRD9YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEPwnO-k_u7IU9uQOwIw8Gcqyxj0VM5w',
    appId: '1:458679375327:android:3f33b2b053c7f072ab606a',
    messagingSenderId: '458679375327',
    projectId: 'client1-d8775',
    storageBucket: 'client1-d8775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmIdFnTNfy8Uwfs7dIXPufwmT_UaYIFU',
    appId: '1:458679375327:ios:2980866f21ffbb54ab606a',
    messagingSenderId: '458679375327',
    projectId: 'client1-d8775',
    storageBucket: 'client1-d8775.appspot.com',
    iosClientId: '458679375327-h1c0628m3vlpkap4novsf9tcc6rkcufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabineClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmIdFnTNfy8Uwfs7dIXPufwmT_UaYIFU',
    appId: '1:458679375327:ios:2980866f21ffbb54ab606a',
    messagingSenderId: '458679375327',
    projectId: 'client1-d8775',
    storageBucket: 'client1-d8775.appspot.com',
    iosClientId: '458679375327-h1c0628m3vlpkap4novsf9tcc6rkcufn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabineClient',
  );
}
